// <auto-generated />
using CompanyManagerTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyManagerTool.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompanyManagerTool.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activities")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("County")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("VMVT")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("WrongEmail")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("CompanyDb");
                });

            modelBuilder.Entity("CompanyManagerTool.Models.VmvtDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("vmvtDivision")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VmvtDb");
                });
#pragma warning restore 612, 618
        }
    }
}
